### ISSUE TITLE
L1Ant1.dat data file

### ISSUE THREAD

**Issue by mfkiwl** [haojie1/GNSS_SDR_C#1]
Many thanks for sharing your contributions to GNSS-SDR receiver.

Could you please share the file "L1Ant1.dat"? I compiled the program and am interested to have the IF file to start.

**Comment by haojie1** [comment]
OK，I'm trying, please wait.

**Comment by haojie1** [comment]
The IF signal file has been uploaded already.

**Comment by mfkiwl** [comment]
Many thanks. I downloaded the IF data file. The Acq works great; but when it starts to track the satellites, there are errors "Not able to read the specified number of samples for tracking, exiting!" 

I debugged and confirmed that the error come from the IF file: end of file, which made me crazy. Obviously the IF data file is large enough and fseek function works OK.

I downloaded the IF data file using git LFS and checked that the actual size is OK (381MB). Are you able to reproduce this error by downloading the IF data file from Github? I mean the uploading/downloading of the large files can cause problems.

**Comment by haojie1** [comment]
OK，I'll check it later. Thanks for your feedback.

**Comment by haojie1** [comment]
Sorry!, it works for me. I either use "git lfs" to download "L1Ant1.dat" or redownload this project completely and it works!
I recommend you download this project again, or you can give me information about your environment.
1) Using "git lfs" to download "L1Ant1.dat"
First. I used "git lfs pull --include="L1Ant1.dat" to pull signal file. Then I compiled this project and run "./GNSS_Receiver".  It works!
![图片](https://user-images.githubusercontent.com/46878455/232476153-05bb3e6b-c03b-4af8-a80b-defc0565cb92.png)
2) Git clone this project complete again
After I clone this project, the signal file is already in the cloned file. So, I just compile it and run "./GNSS_Receiver". It works! the result is same as the above one.
So, I'm sorry and I cannot reproduce this error. Please redownload this project and compile it. If you still have problem, please let me know and I'd like to help you.

**Comment by mfkiwl** [comment]
Many thanks for your quick response and confirming the file is working OK.

The ACQ results are different from mine. I can't acq SAT 4 but SAT 8 is OK. So I guess the IF data file I downloaded must have a problem. I'll figure it out.

**Comment by mfkiwl** [comment]
By the way, are you convenient to share the data file by other methods? Such as Google drive or terabox (1TB free)? Currently the IF data file can't be downloaded from github because of the bandwidth limit (downloaded by me for several times and used up of the bandwidth).

**Comment by haojie1** [comment]
Sorry, I'm in China, so I don't have Google drive or terabox. Are you Chinese? If you are Chinese, I'd like to share this file through Aliyun driver.

**Comment by mfkiwl** [comment]
Sorry I can't register/download on Aliyun drive. But Baidu pan will be OK for me if convenient for you.

**Comment by haojie1** [comment]
Let'm try, please wait.

**Comment by haojie1** [comment]
I have registered terabox and uploaded the signal file. The link is https://terabox.com/s/156I5I6-Usbv0NY9eljaIQg. Please check if you can download the signal file. If you have a problem, let me know.

**Comment by mfkiwl** [comment]
Many thanks. I downloaded the file and got the same POS results as you. 

I'll close this issue now
